name: unicorn-binance-websocket-api

channels:
  - lucit
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - lucit::unicorn-fy >=0.15.0
  - lucit::unicorn-binance-rest-api >=2.7.0
  - cheroot
  - colorama
  - Cython
  - flask
  - flask-restful
  - orjson
  - psutil
  - PySocks
  - requests>=2.31.0
  - simplejson
  - websocket-client
  - websockets==11.0.3
  - typing_extensions
