blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community via the UNICORN Binance WebSocket API and ask general questions.
  - name: UNICORN Binance WebSocket API Discussions
    url: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/discussions
    about: Ask general questions.
  - name: UNICORN Binance WebSocket API documentation
    url: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api
    about: The complete UNICORN Binance WebSocket API documentation.
